import logging

from database.db import get_connection, schema_name
from database.pdf_files import export_legacy_blobs
from database.sqlite_import import import_sqlite_if_empty

logger = logging.getLogger(__name__)


def create_tables():
    """
    Create the application tables if they do not exist.
    Safe to call on every startup.
    """
    conn = get_connection()
    try:
        _create_tables(conn)
    finally:
        conn.close()
    logger.info("PostgreSQL application tables verified.")


def _create_tables(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS accounts (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email           TEXT NOT NULL UNIQUE,
            password_hash   TEXT,
            auth_provider   TEXT NOT NULL DEFAULT 'local',
            session_version INTEGER NOT NULL DEFAULT 1,
            created_at      TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            age              INTEGER NOT NULL,
            income           DOUBLE PRECISION NOT NULL,
            expenses         DOUBLE PRECISION NOT NULL,
            savings          DOUBLE PRECISION NOT NULL,
            risk_appetite    TEXT NOT NULL,
            financial_goals  TEXT NOT NULL,
            account_id       BIGINT REFERENCES accounts(id),
            created_at       TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS reports (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id      BIGINT NOT NULL UNIQUE
                             REFERENCES users(id) ON DELETE CASCADE,
            health_json  TEXT NOT NULL,
            ai_report    TEXT NOT NULL,
            pdf_blob     BYTEA,
            pdf_path     TEXT,
            generated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_history (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id    BIGINT NOT NULL
                           REFERENCES users(id) ON DELETE CASCADE,
            role       TEXT NOT NULL CHECK (role IN ('user', 'ai')),
            message    TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_reports_user_id
        ON reports(user_id)
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_chat_history_user_id
        ON chat_history(user_id, id DESC)
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_users_account_id
        ON users(account_id)
    """)

    from database.repository import attach_orphan_profiles

    conn.commit()
    if schema_name() == "public":
        import_sqlite_if_empty(conn)
    attach_orphan_profiles(conn)
    export_legacy_blobs(conn)
    conn.commit()
