import logging
import re

from database.db import get_connection, schema_name
from database.pdf_files import export_legacy_blobs
from database.sqlite_import import import_sqlite_if_empty

logger = logging.getLogger(__name__)


def _allow_chat_jobs(conn):
    """Existing databases were created when jobs.kind allowed only reports."""
    rows = conn.execute(
        """
        SELECT conname AS name
        FROM pg_constraint
        WHERE conrelid = 'jobs'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%kind%'
        """
    ).fetchall()
    for row in rows:
        name = row["name"]
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            continue
        conn.execute(f"ALTER TABLE jobs DROP CONSTRAINT {name}")
    conn.execute(
        "ALTER TABLE jobs ADD CONSTRAINT jobs_kind_check CHECK (kind IN ('report', 'chat'))"
    )


def create_tables():
    """
    Create the application tables if they do not exist.
    Safe to call on every startup. A SQLite file is opened only when
    SQLITE_IMPORT is on and the schema is public.
    """
    conn = get_connection()
    try:
        _create_tables(conn)
    finally:
        conn.close()
    logger.info("PostgreSQL application tables verified.")


def _create_tables(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS accounts (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email           TEXT NOT NULL UNIQUE,
            password_hash   TEXT,
            auth_provider   TEXT NOT NULL DEFAULT 'local',
            session_version INTEGER NOT NULL DEFAULT 1,
            created_at      TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            age              INTEGER NOT NULL,
            income           DOUBLE PRECISION NOT NULL,
            expenses         DOUBLE PRECISION NOT NULL,
            savings          DOUBLE PRECISION NOT NULL,
            risk_appetite    TEXT NOT NULL,
            financial_goals  TEXT NOT NULL,
            account_id       BIGINT REFERENCES accounts(id),
            created_at       TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS reports (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id      BIGINT NOT NULL UNIQUE
                             REFERENCES users(id) ON DELETE CASCADE,
            health_json  TEXT NOT NULL,
            ai_report    TEXT NOT NULL,
            pdf_path     TEXT,
            generated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_history (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id    BIGINT NOT NULL
                           REFERENCES users(id) ON DELETE CASCADE,
            role       TEXT NOT NULL CHECK (role IN ('user', 'ai')),
            message    TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_reports_user_id
        ON reports(user_id)
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_chat_history_user_id
        ON chat_history(user_id, id DESC)
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_users_account_id
        ON users(account_id)
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS jobs (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind          TEXT NOT NULL CHECK (kind IN ('report', 'chat')),
            account_id    BIGINT REFERENCES accounts(id),
            user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            status        TEXT NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
            payload       TEXT,
            error_code    TEXT,
            error_detail  TEXT,
            attempts      INTEGER NOT NULL DEFAULT 0,
            started_at    TIMESTAMPTZ,
            finished_at   TIMESTAMPTZ,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_one_active_report
        ON jobs (user_id)
        WHERE kind = 'report' AND status IN ('queued', 'running')
    """)
    conn.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS payload TEXT")
    _allow_chat_jobs(conn)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS api_credentials (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id   BIGINT NOT NULL REFERENCES accounts(id),
            label        TEXT NOT NULL,
            key_hash     TEXT NOT NULL,
            scopes       TEXT NOT NULL,
            revoked_at   TIMESTAMPTZ,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_api_credentials_account
        ON api_credentials (account_id)
    """)

    from config import Config
    from database.repository import attach_orphan_profiles

    conn.commit()
    if schema_name() == "public" and Config.SQLITE_IMPORT:
        import_sqlite_if_empty(conn)
    attach_orphan_profiles(conn)
    export_legacy_blobs(conn)
    _drop_pdf_blob_if_clear(conn)
    conn.commit()


def _drop_pdf_blob_if_clear(conn):
    """Drop reports.pdf_blob once no row still keeps bytes without a file path."""
    present = conn.execute(
        """
        SELECT 1 AS present
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'reports'
          AND column_name = 'pdf_blob'
        """
    ).fetchone()
    if not present:
        return
    leftover = conn.execute(
        """
        SELECT COUNT(*) AS n FROM reports
        WHERE pdf_blob IS NOT NULL AND length(pdf_blob) > 0
          AND (pdf_path IS NULL OR pdf_path = '')
        """
    ).fetchone()["n"]
    if leftover:
        logger.error(
            "reports.pdf_blob still holds %s file(s) with no path; column kept",
            leftover,
        )
        return
    conn.execute("ALTER TABLE reports DROP COLUMN pdf_blob")
